# Auto-generated by SHOPZOO AI
# Market: XAUUSD
# Style: scalping
# Timeframe: M5
# Risk per trade: 0.5%

import pandas as pd

def load_data(csv_path):
    data = pd.read_csv(csv_path)
    data["EMA_FAST"] = data["close"].ewm(span=9).mean()
    data["EMA_SLOW"] = data["close"].ewm(span=21).mean()
    return data

def generate_signals(data):
    signals = []
    for i in range(1, len(data)):
        if data["EMA_FAST"][i] > data["EMA_SLOW"][i] and data["EMA_FAST"][i-1] <= data["EMA_SLOW"][i-1]:
            signals.append("BUY")
        elif data["EMA_FAST"][i] < data["EMA_SLOW"][i] and data["EMA_FAST"][i-1] >= data["EMA_SLOW"][i-1]:
            signals.append("SELL")
        else:
            signals.append("HOLD")
    return signals

def run_backtest(data):
    signals = generate_signals(data)
    data["signal"] = ["HOLD"] + signals
    return data

if __name__ == "__main__":
    data = load_data("data.csv")  # CSV with columns: time, open, high, low, close
    result = run_backtest(data)
    print(result.tail())