# agents/codegen_agent.py

# ==================================================
# TRADING CODEGEN (SAFE & STABLE)
# ==================================================

def generate_python_algo(algo: dict, strategy: dict) -> str:
    """
    Generate a simple Python trading algorithm template
    """

    risk = algo.get("risk", "1%")
    timeframe = strategy.get("timeframe", "M15")
    market = strategy.get("market", "forex")
    style = strategy.get("style", "intraday")

    code = f'''
# Auto-generated by SHOPZOO AI
# Market: {market}
# Style: {style}
# Timeframe: {timeframe}
# Risk per trade: {risk}

import pandas as pd

def load_data(csv_path):
    data = pd.read_csv(csv_path)
    data["EMA_FAST"] = data["close"].ewm(span=9).mean()
    data["EMA_SLOW"] = data["close"].ewm(span=21).mean()
    return data

def generate_signals(data):
    signals = []
    for i in range(1, len(data)):
        if data["EMA_FAST"][i] > data["EMA_SLOW"][i] and data["EMA_FAST"][i-1] <= data["EMA_SLOW"][i-1]:
            signals.append("BUY")
        elif data["EMA_FAST"][i] < data["EMA_SLOW"][i] and data["EMA_FAST"][i-1] >= data["EMA_SLOW"][i-1]:
            signals.append("SELL")
        else:
            signals.append("HOLD")
    return signals

def run_backtest(data):
    signals = generate_signals(data)
    data["signal"] = ["HOLD"] + signals
    return data

if __name__ == "__main__":
    data = load_data("data.csv")
    result = run_backtest(data)
    print(result.tail())
'''
    return code.strip()


# ==================================================
# WEBSITE CODEGEN – MULTI-PAGE PROFESSIONAL WEBSITE
# ==================================================

def generate_website_html_css(business: str, theme: str = "blue") -> dict:
    """
    Generate multi-page professional website (HTML + CSS)
    Pages: Home, About, Services, Contact
    """

    # ---------- Theme ----------
    bg_color = "#f5f7fb"
    primary = "#003366"
    card_bg = "#ffffff"
    text_color = "#333333"

    if theme == "green":
        primary = "#0a7d3b"
    elif theme == "red":
        primary = "#8b0000"
    elif theme == "dark":
        bg_color = "#121212"
        primary = "#ffffff"
        card_bg = "#1e1e1e"
        text_color = "#e0e0e0"

    # ---------- Common Layout ----------
    header = f"""
<header class="top-header">
    <h1>{business}</h1>
    <p>Reliable • Fast • Trusted Services</p>
</header>
"""

    nav = """
<nav class="navbar">
    <a href="index.html">Home</a>
    <a href="about.html">About</a>
    <a href="services.html">Services</a>
    <a href="contact.html">Contact</a>
</nav>
"""

    footer = f"""
<footer>
    <p>© {business}. All rights reserved.</p>
</footer>
"""

    # ---------- Pages ----------
    index_html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>{business} - Home</title>
<link rel="stylesheet" href="style.css">
</head>
<body>
{header}
{nav}
<div class="container">
    <div class="card">
        <h2>Welcome</h2>
        <p>Welcome to <strong>{business}</strong>. We provide fast and reliable services.</p>
    </div>
</div>
{footer}
</body>
</html>
"""

    about_html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>About - {business}</title>
<link rel="stylesheet" href="style.css">
</head>
<body>
{header}
{nav}
<div class="container">
    <div class="card">
        <h2>About Us</h2>
        <p>{business} is committed to quality service and customer satisfaction.</p>
    </div>
</div>
{footer}
</body>
</html>
"""

    services_html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Services - {business}</title>
<link rel="stylesheet" href="style.css">
</head>
<body>
{header}
{nav}
<div class="container">
    <div class="card">
        <h2>Our Services</h2>
        <ul>
            <li>Online Application Services</li>
            <li>Printing & Scanning</li>
            <li>Customer Support</li>
            <li>Fast & Secure Work</li>
        </ul>
    </div>
</div>
{footer}
</body>
</html>
"""

    contact_html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Contact - {business}</title>
<link rel="stylesheet" href="style.css">
</head>
<body>
{header}
{nav}
<div class="container">
    <div class="card">
        <h2>Contact Us</h2>
        <p>Visit our office or contact us on WhatsApp.</p>
        <a class="whatsapp-btn" href="https://wa.me/91XXXXXXXXXX" target="_blank">
            📞 Chat on WhatsApp
        </a>
    </div>
</div>
{footer}
</body>
</html>
"""

    # ---------- CSS ----------
    css = f"""
body {{
    font-family: Arial, sans-serif;
    background-color: {bg_color};
    color: {text_color};
    margin: 0;
}}

.top-header {{
    background-color: {primary};
    color: white;
    padding: 30px 15px;
    text-align: center;
}}

.navbar {{
    background-color: #ffffff;
    text-align: center;
    padding: 10px;
    box-shadow: 0 2px 6px rgba(0,0,0,0.08);
}}

.navbar a {{
    margin: 0 15px;
    text-decoration: none;
    color: {primary};
    font-weight: bold;
}}

.container {{
    max-width: 900px;
    margin: 30px auto;
    padding: 0 15px;
}}

.card {{
    background-color: {card_bg};
    padding: 25px;
    border-radius: 12px;
    box-shadow: 0 4px 12px rgba(0,0,0,0.08);
}}

.whatsapp-btn {{
    display: inline-block;
    margin-top: 15px;
    padding: 14px 22px;
    background-color: #25D366;
    color: white;
    text-decoration: none;
    border-radius: 8px;
    font-weight: bold;
}}

footer {{
    text-align: center;
    padding: 20px;
    font-size: 14px;
    color: #777;
}}
"""

    return {
        "pages": {
            "index.html": index_html,
            "about.html": about_html,
            "services.html": services_html,
            "contact.html": contact_html
        },
        "css": css
    }
