# agents/mql5_codegen_agent.py

def generate_mql5_ea(algo: dict, strategy: dict) -> str:
    """
    Generate MQL5 Expert Advisor skeleton
    """

    risk = algo.get("risk", "1%")
    timeframe = strategy.get("timeframe", "M15")
    market = strategy.get("market", "FOREX")
    style = strategy.get("style", "intraday")

    ea_code = f'''
//+------------------------------------------------------------------+
//| Auto-generated by SHOPZOO AI                                     |
//| Market: {market}                                                 |
//| Style: {style}                                                   |
//| Timeframe: {timeframe}                                           |
//| Risk per trade: {risk}                                           |
//+------------------------------------------------------------------+

#property strict

input double RiskPercent = {risk.replace('%','')};
input int FastEMA = 9;
input int SlowEMA = 21;

double lotSize;

//+------------------------------------------------------------------+
int OnInit()
{{
   Print("SHOPZOO AI EA initialized");
   return(INIT_SUCCEEDED);
}}

//+------------------------------------------------------------------+
void OnTick()
{{
   double emaFast = iMA(Symbol(), 0, FastEMA, 0, MODE_EMA, PRICE_CLOSE, 0);
   double emaSlow = iMA(Symbol(), 0, SlowEMA, 0, MODE_EMA, PRICE_CLOSE, 0);

   double emaFastPrev = iMA(Symbol(), 0, FastEMA, 0, MODE_EMA, PRICE_CLOSE, 1);
   double emaSlowPrev = iMA(Symbol(), 0, SlowEMA, 0, MODE_EMA, PRICE_CLOSE, 1);

   // BUY condition
   if(emaFast > emaSlow && emaFastPrev <= emaSlowPrev)
   {{
      Print("BUY signal detected");
      // OrderSend logic here
   }}

   // SELL condition
   if(emaFast < emaSlow && emaFastPrev >= emaSlowPrev)
   {{
      Print("SELL signal detected");
      // OrderSend logic here
   }}
}}
'''
    return ea_code.strip()
